# Generated by Django 3.0.5 on 2020-08-01 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import print.models
import print.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=print.models.path_and_rename('printing'), validators=[print.validators.validate_size])),
                ('doc_id', models.UUIDField(default=uuid.uuid4)),
                ('name_of_file', models.CharField(max_length=500)),
                ('copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(choices=[('c', 'Colored'), ('b', 'Black and White')], default='c', max_length=2)),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('paper_type', models.CharField(choices=[('p', 'Plain Paper'), ('e', 'Premium Glossy')], default='p', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('deleted', models.BooleanField(default=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
