# Generated by Django 3.0.5 on 2020-08-01 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GATEWAYNAME', models.CharField(max_length=30)),
                ('RESPMSG', models.TextField()),
                ('BANKNAME', models.CharField(max_length=500)),
                ('PAYMENTMODE', models.CharField(max_length=30)),
                ('RESPCODE', models.IntegerField()),
                ('TXNID', models.CharField(max_length=70)),
                ('TXNAMOUNT', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ORDERID', models.UUIDField()),
                ('STATUS', models.CharField(max_length=30)),
                ('BANKTXNID', models.CharField(max_length=256)),
                ('TXNDATE', models.DateTimeField()),
                ('CHECKSUMHASH', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
